# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Socialism
description: > # this means to ignore newlines until "baseurl:"
  a compelling alternative to democratic capitalism
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opensocialism.com" # the base hostname & protocol for your site
github_username:  open-socialism

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
