version: "2"

services:
  dev:
    build: .
    volumes:
      - .:/work
      - ruby2.3.0-gem-cache:/var/cache/gems/2.3.0
    working_dir: /work
    environment:
      - GEM_HOME=/var/cache/gems/2.3.0
      - GEM_PATH=/usr/local/lib/ruby/gems/2.3.0:/var/cache/gems/2.3.0
    ports:
      - "4000:4000"
  prod:
    environment:
      - JEKYLL_ENV=production
    extends:
      service: dev

volumes:
  ruby2.3.0-gem-cache:
    external: true
